version: "3"

services:
  backend-service:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod

    expose:
      - 8080

  frontend-service:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_GOOGLE_MAPS_API_KEY=${REACT_APP_GOOGLE_MAPS_API_KEY}
    ports:
      - 80:80
