apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: {{ .Values.environment.backend.count }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: {{ .Values.environment.backend.image }}
          ports:
            - containerPort: 8080
          env:
            - name: GoogleMaps__ApiKey
              value: {{ .Values.environment.backend.GoogleMaps__ApiKey }}
            - name: GoogleMaps__ApiUrl
              value: {{ .Values.environment.backend.GoogleMaps__ApiUrl }}
