name: Backend Deployment

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/**"

jobs:
  build-and-push-backend:
    name: Build and Push Backend Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ vars.DOCKER_HUB_BACK_END_IMAGE }}
