name: Terraform and Kubernetes Deployment

on:
  push:
    branches:
      - main
    paths:
      - "k8s/**"
      - "terraform/**"
      - ".github/workflows/**"

jobs:
  terraform-setup:
    name: Terraform Operations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_API_TOKEN }}
          terraform_wrapper: false

      - name: Initialize Terraform
        run: |
          terraform -chdir=./terraform init
          terraform refresh

      - name: Terraform Plan
        run: terraform -chdir=./terraform plan

      - name: Apply Terraform Changes
        id: terraform-apply
        run: |
          terraform -chdir=./terraform apply -auto-approve
          echo "::set-output name=cluster_name::$(terraform -chdir=./terraform output -raw cluster_name)"

    outputs:
      cluster_name: ${{ steps.terraform-apply.outputs.cluster_name }}

  deploy:
    name: Deploy to Kubernetes
    needs: terraform-setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Set up Kubeconfig
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.24.0"

      - name: Update kube config with Terraform output
        run: aws eks update-kubeconfig --name ${{ needs.terraform-setup.outputs.cluster_name }}

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: "3.7.0"

      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install transport-optimizer ./app-chart
